name: Publish NuGet Package

on:
  push:
    branches:
      - master # Запускать на основной ветке
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  tag_and_publish:
    runs-on: ubuntu-latest

    env:
      MAJOR_VERSION: 1 # Задаем мажорную версию здесь
      MINOR_VERSION: 0 # Задаем минорную версию здесь

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Укажите нужную версию .NET SDK

      - name: Get latest tag
        id: get_tag
        run: |
          # Получаем последний тег, если он существует
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$tag" ]; then
            tag="v${MAJOR_VERSION}.${MINOR_VERSION}.0"
          fi
          echo "Последний тег: $tag"
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Fetch all tags
        run: git fetch --tags

      - name: Calculate next build number
        id: next_tag
        run: |
          # Удаляем префикс 'v' из последнего тега и извлекаем номер билда
          tag_without_v="${tag#v}"
          IFS='.' read -ra VERSION <<< "$tag_without_v"
      
          # Используем указанные в воркфлоу мажор и минор, а билд инкрементируем
          major="${MAJOR_VERSION}"
          minor="${MINOR_VERSION}"
          build=${VERSION[2]}
      
          # Инкремент номера билда и проверка существования тега
          next_build=$((build + 1))
          new_tag="v$major.$minor.$next_build"
      
          # Проверка существования тега на удалённом репозитории и инкремент при необходимости
          while git ls-remote --tags origin | grep -q "refs/tags/$new_tag"; do
            next_build=$((next_build + 1))
            new_tag="v$major.$minor.$next_build"
          done
      
          echo "next_tag=$new_tag" >> $GITHUB_ENV
          echo "Новый тег: $new_tag"



      - name: Create new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.next_tag }}
          git push origin ${{ env.next_tag }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --no-build --configuration Release -o ./nuget

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push "./nuget/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "$GITHUB_TOKEN"
